"""
PilotForge API Documentation Generator
Automatically generates comprehensive API documentation from OpenAPI spec
"""
import json
import httpx
from pathlib import Path
from datetime import datetime


def fetch_openapi_spec(base_url='http://localhost:8000'):
    """Fetch OpenAPI specification from running API"""
    try:
        response = httpx.get(f'{base_url}/openapi.json')
        return response.json()
    except Exception as e:
        print(f"❌ Error fetching OpenAPI spec: {e}")
        print("   Make sure the API is running: python -m uvicorn src.main:app")
        return None


def generate_endpoint_docs(spec):
    """Generate markdown documentation for all endpoints"""
    docs = []
    
    for path, methods in spec['paths'].items():
        for method, details in methods.items():
            if method.upper() not in ['GET', 'POST', 'PUT', 'DELETE', 'PATCH']:
                continue
            
            # Build endpoint documentation
            endpoint_doc = f"""
### `{method.upper()} {path}`

**Summary:** {details.get('summary', 'No summary')}

**Description:** {details.get('description', 'No description')}

"""
            
            # Request body
            if 'requestBody' in details:
                endpoint_doc += "**Request Body:**\n```json\n"
                # Try to get example or schema
                content = details['requestBody'].get('content', {})
                if 'application/json' in content:
                    schema_ref = content['application/json'].get('schema', {})
                    endpoint_doc += json.dumps(schema_ref, indent=2)
                endpoint_doc += "\n```\n\n"
            
            # Parameters
            if 'parameters' in details:
                endpoint_doc += "**Parameters:**\n"
                for param in details['parameters']:
                    required = "required" if param.get('required', False) else "optional"
                    endpoint_doc += f"- `{param['name']}` ({param.get('in', 'query')}, {required}): {param.get('description', 'No description')}\n"
                endpoint_doc += "\n"
            
            # Responses
            if 'responses' in details:
                endpoint_doc += "**Responses:**\n"
                for status, response in details['responses'].items():
                    endpoint_doc += f"- **{status}**: {response.get('description', 'No description')}\n"
                endpoint_doc += "\n"
            
            docs.append(endpoint_doc)
    
    return "\n---\n".join(docs)


def generate_api_reference(spec):
    """Generate complete API reference document"""
    doc = f"""# 📡 PilotForge API Reference

> Auto-generated API documentation
> 
> Last updated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}

---

## 📋 Table of Contents

1. [Overview](#overview)
2. [Base URL](#base-url)
3. [Authentication](#authentication)
4. [Endpoints](#endpoints)
5. [Models](#models)
6. [Error Handling](#error-handling)

---

## 🎯 Overview

**API Name:** {spec['info']['title']}  
**Version:** {spec['info']['version']}  
**Description:** {spec['info'].get('description', 'No description')}

---

## 🌐 Base URL

```
Production: https://pilotforge.onrender.com/api/v1
Development: http://localhost:8000/api/v1
```

---

## 🔐 Authentication

Current version: **No authentication required**

Future versions will support:
- API Keys
- OAuth 2.0
- JWT tokens

---

## 📡 Endpoints

{generate_endpoint_docs(spec)}

---

## 📦 Models

"""
    
    # Add schemas/models
    if 'components' in spec and 'schemas' in spec['components']:
        for model_name, model_schema in spec['components']['schemas'].items():
            doc += f"""
### {model_name}

```json
{json.dumps(model_schema, indent=2)}
```

"""
    
    doc += """
---

## ⚠️ Error Handling

### Standard Error Response

```json
{
  "detail": "Error message here"
}
```

### Common HTTP Status Codes

| Code | Meaning | Description |
|------|---------|-------------|
| 200 | OK | Request successful |
| 201 | Created | Resource created successfully |
| 400 | Bad Request | Invalid input data |
| 404 | Not Found | Resource not found |
| 422 | Validation Error | Input validation failed |
| 500 | Server Error | Internal server error |

---

**Generated by:** PilotForge API Documentation Generator  
**Source:** OpenAPI Specification  
**Contact:** support@pilotforge.com
"""
    
    return doc


def generate_postman_collection(spec):
    """Generate Postman collection from OpenAPI spec"""
    collection = {
        "info": {
            "name": "PilotForge API",
            "description": spec['info'].get('description', ''),
            "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
        },
        "item": []
    }
    
    for path, methods in spec['paths'].items():
        for method, details in methods.items():
            if method.upper() not in ['GET', 'POST', 'PUT', 'DELETE']:
                continue
            
            request_item = {
                "name": details.get('summary', path),
                "request": {
                    "method": method.upper(),
                    "header": [
                        {
                            "key": "Content-Type",
                            "value": "application/json"
                        }
                    ],
                    "url": {
                        "raw": "{{base_url}}" + path,
                        "host": ["{{base_url}}"],
                        "path": path.strip('/').split('/')
                    },
                    "description": details.get('description', '')
                }
            }
            
            # Add request body example if exists
            if 'requestBody' in details:
                content = details['requestBody'].get('content', {})
                if 'application/json' in content:
                    request_item['request']['body'] = {
                        "mode": "raw",
                        "raw": json.dumps({}, indent=2)
                    }
            
            collection['item'].append(request_item)
    
    return collection


def main():
    """Main documentation generator"""
    print("📚 PilotForge API Documentation Generator")
    print("=" * 60)
    
    # Fetch OpenAPI spec
    print("\n1️⃣ Fetching OpenAPI specification...")
    spec = fetch_openapi_spec()
    
    if not spec:
        print("\n❌ Failed to generate documentation")
        print("   Start the API and try again")
        return
    
    print(f"✅ Fetched spec for: {spec['info']['title']} v{spec['info']['version']}")
    
    # Generate API reference
    print("\n2️⃣ Generating API reference...")
    api_reference = generate_api_reference(spec)
    
    # Save API reference
    output_path = Path('API_REFERENCE.md')
    output_path.write_text(api_reference)
    print(f"✅ Saved: {output_path}")
    
    # Generate Postman collection
    print("\n3️⃣ Generating Postman collection...")
    postman_collection = generate_postman_collection(spec)
    
    # Save Postman collection
    postman_path = Path('PilotForge.postman_collection.json')
    postman_path.write_text(json.dumps(postman_collection, indent=2))
    print(f"✅ Saved: {postman_path}")
    
    # Generate OpenAPI spec file
    print("\n4️⃣ Saving OpenAPI specification...")
    openapi_path = Path('openapi.json')
    openapi_path.write_text(json.dumps(spec, indent=2))
    print(f"✅ Saved: {openapi_path}")
    
    # Summary
    print("\n" + "=" * 60)
    print("🎉 Documentation generation complete!")
    print("\nGenerated files:")
    print(f"  📄 {output_path} - Complete API reference")
    print(f"  📮 {postman_path} - Postman collection")
    print(f"  📋 {openapi_path} - OpenAPI specification")
    print("\n💡 Import Postman collection to test all endpoints!")


if __name__ == '__main__':
    main()